# #
# Even Fibonacci numbers
# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 0 + 1 = 1, 1+ 2 = 3, 2+3 = 5
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


num1 = 0
num2 = 1
num3 = 0
sum = 0
limit = 4000000
while num3 < limit:
    num3 = num2 + num1
    num1 = num2
    num2 = num3

    if num2%2==0:
     sum = sum + num3

print(sum)





